[package]
name = "v2ray-rs-tray"
version.workspace = true
edition.workspace = true

[dependencies]
v2ray-rs-core.workspace = true
v2ray-rs-process.workspace = true
ksni.workspace = true
notify-rust.workspace = true
resvg.workspace = true
tokio.workspace = true
tempfile.workspace = true
log.workspace = true

[dev-dependencies]
chrono.workspace = true
uuid.workspace = true
