[package]
name = "v2ray-rs-process"
version.workspace = true
edition.workspace = true

[dependencies]
v2ray-rs-core.workspace = true
tokio.workspace = true
thiserror.workspace = true
nix.workspace = true
serde.workspace = true
serde_json.workspace = true
log.workspace = true

[dev-dependencies]
tempfile.workspace = true
